language: go
go:
- "1.10"
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_92b391726577_key -iv $encrypted_92b391726577_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
after_success:
- scp -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $TRAVIS_BUILD_DIR/RSOI $SSH_USER@$SSH_HOST:~/
- ssh -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t $SSH_USER@$SSH_HOST './RSOI'
env:
  global:
  - secure: M4uCsDeRM/dAyeTdPMoMYfdDMJMe6s1i4XyMFmEhdgQJdkxG8mpzUwYyPR7UXwdsBmfKpf6Mk+5Hl9QgOnkPSpBfwyFyNVhaIPDQWbuzCB/qN/7P3q/s7Rp7nStUk68imgOngXyQlrvVoW7B9pYrS2DBH5RAq7axt7nDYog4MYKp5Lr9TDAXx3dPJsiA0Xpw/v6C0hdtN7fWymM8RqSJDGYk44t6oDQCp2SytTAjZqIc8Ruj7UeQIOCd9tnl/p83KPeN20S1AzmOHxus4NbIKDCECBX24kMmnV9wW1AtiaqGJYGnDrBokblqQ0a2HxndJ+dsq1LjBSRZOqGafxT/lsiKBcK5zwutc1O5Wk1Kw+BIuQmmAUJ/KBkfuZJJR6YaB6CtbcaMIuZOUXvMII2mDi0jB50JbiIq7SxTmTV/KO9XLyOuO5TIBH5APkqV+6ty0MiiXbGE56Y8lHUu4Ul2LSoT2bT6THT1OXZ2fZrpGzw2B2SEK9x84LUF+wEBr0aSprmNKWEsEoDAXaULLcuS7ILR18prYfDULKUZIdS6xYDb/uM0adc/pEL80M4a02Em2lw7iGmEVk8pQlA3GFZSN+ZYAII86A0Gu4Ne1+sI0Z3nC6dDO0CVxzc+QpvhNHXyYgJBw66Up6xxRRrt063ZKjsWiOzywUBnC1/ceaF//uo=
  - secure: d61NP+VrNMXX6J4ik2CB6UvE4cFrubCBkRQdFZdcppqxDSeKnjSvuJthsZQ5HaLIMVpf0Q2+a7jwcndnNw3dt4jJ3mimpq0lB8iVQ+M82THu9SPSoofHWDrWTLbyKqM+lVec6ttkkw89uC836RXPB4bksa8L2RaMf+ELQQDwMr/1dorAg363zBXCTygfBFkk62KkQanDSgN0L1gjVEAiuV1E6YgzMJRiceIfLx8AvPu6TjSnIkJpg+bosyqjWl7B8AjHqn1e3XHt61DKWZbXtyve6SL4DQ4qjnZPtcN049YBIixOpWgrjNvkCSB0TRm43Z/PtTjIQw9McPtRdNc+/iOGaec3Ja80lg1puCO0CO8FhUqJrKlZ9Fwl7CddOjLutpvZQN7OUqkh8klKsAzoSYWrslnv3xWM2R9BM8Ydj/12QMTZwNZiVIDCk1BsO4YCqGP2YZVvZpzR7haipULvTV6ScU5rWqpQ5XA9sPChQf3smFaBloZVIgCiGG5Ou2uaAoOiYE1TRs1O7PS1Ftdh5hEXkbPxuKab7aY8YFngOKNDNYRytqV2n1xj5cqseRPfjWIBIfHWqADeN6nMKexBiuAzXmmwJQue9nJ2s2h/yZiU+zJggVZJaNfi2RbbkIU5pY/iQ8xF0www1bGRtuQDgKxZ9vdGNx5JZ8KM0NeEGlA=