language: go

go:
  - tip

script:
  - make build test

deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-go.git
  api_key:
    secure: en33aHSYgycXmQ19XXiKaQXCTfoM+Pru6SZPsaLeE+w2wcFdEN+KkHYfza07tGxEa+oFXlF32BDHZKtxCQpH9MP5ziZGL7T/QfbBiBtT90JIQoY0E+bN5DvG3BTcz5XH0NFgSzaES4dGqTCJIHQ3dvV2vNwA9RHZAiGzZkcLgFt2xlbhBM8X4c/NMkqgjlbEJqWD0LWzH343sm5sIa8hc7ueHSIW1zK2q4GTr3MHsloQG2EowrK1hqiAvUaB4l+bnaRyQSl+O2hUgiTKFE6dZ6IHdkuie7ejCnYKllqFJ2m8tAEiQRsZHamzTnSKexA3s6eNPZyt4rncGqBSmAnIfJk2M47p4N9nhqAQrAECSC4uDvZI7KaHD8idnc46P9yK/QeKgo314z45IiL80pSH9yNmuFwl5rvbSWGBVvzKUueU3cxwkSIkrK0NIrbVw2wM2AgkclcnGnql6BJmoOelOTHvZHoK5BbfzxaSl9Mik8tukRQrUMsnGprHcQdfIHOhKhQDaa1OQNd2mn6IMBpLBr9jkuOfI3IxKH4q7olMHVw1cyn7DeYU+kKSbMUsGbF7kpJjrk+tWjb1fxG54+W2RIChVAJyqQFZcizF/ewaFsJVwvhqKSPaAZ71rL1ZnoxuxPa2v+bf7C8m6z5tiVvIjsR8RYFqCidmHxu2X5o2RCE=
  app: rsoi-aivanov
  on: master