// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/post/proto/post.proto

package post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListPostsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{0}
}
func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (dst *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(dst, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

func (m *ListPostsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPostsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListPostsResponse struct {
	Posts                []*SinglePost `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	PageSize             int32         `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32         `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{1}
}
func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (dst *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(dst, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*SinglePost {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *ListPostsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPostsResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type GetPostRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{2}
}
func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (dst *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(dst, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type SinglePost struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserUid              string               `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string               `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SinglePost) Reset()         { *m = SinglePost{} }
func (m *SinglePost) String() string { return proto.CompactTextString(m) }
func (*SinglePost) ProtoMessage()    {}
func (*SinglePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{3}
}
func (m *SinglePost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePost.Unmarshal(m, b)
}
func (m *SinglePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePost.Marshal(b, m, deterministic)
}
func (dst *SinglePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePost.Merge(dst, src)
}
func (m *SinglePost) XXX_Size() int {
	return xxx_messageInfo_SinglePost.Size(m)
}
func (m *SinglePost) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePost.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePost proto.InternalMessageInfo

func (m *SinglePost) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SinglePost) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *SinglePost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SinglePost) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SinglePost) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SinglePost) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type CreatePostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	UserUid              string   `protobuf:"bytes,4,opt,name=userUid,proto3" json:"userUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{4}
}
func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(dst, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreatePostRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type UpdatePostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{5}
}
func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(dst, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdatePostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UpdatePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{6}
}
func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(dst, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

type DeletePostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{7}
}
func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(dst, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeletePostRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeletePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{8}
}
func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (dst *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(dst, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

type CheckExistsRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckExistsRequest) Reset()         { *m = CheckExistsRequest{} }
func (m *CheckExistsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckExistsRequest) ProtoMessage()    {}
func (*CheckExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{9}
}
func (m *CheckExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckExistsRequest.Unmarshal(m, b)
}
func (m *CheckExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckExistsRequest.Marshal(b, m, deterministic)
}
func (dst *CheckExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckExistsRequest.Merge(dst, src)
}
func (m *CheckExistsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckExistsRequest.Size(m)
}
func (m *CheckExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckExistsRequest proto.InternalMessageInfo

func (m *CheckExistsRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CheckExistsResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckExistsResponse) Reset()         { *m = CheckExistsResponse{} }
func (m *CheckExistsResponse) String() string { return proto.CompactTextString(m) }
func (*CheckExistsResponse) ProtoMessage()    {}
func (*CheckExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{10}
}
func (m *CheckExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckExistsResponse.Unmarshal(m, b)
}
func (m *CheckExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckExistsResponse.Marshal(b, m, deterministic)
}
func (dst *CheckExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckExistsResponse.Merge(dst, src)
}
func (m *CheckExistsResponse) XXX_Size() int {
	return xxx_messageInfo_CheckExistsResponse.Size(m)
}
func (m *CheckExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckExistsResponse proto.InternalMessageInfo

func (m *CheckExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type GetTokenRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{11}
}
func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(dst, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetTokenRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{12}
}
func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(dst, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetOwnerRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerRequest) Reset()         { *m = GetOwnerRequest{} }
func (m *GetOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*GetOwnerRequest) ProtoMessage()    {}
func (*GetOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{13}
}
func (m *GetOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerRequest.Unmarshal(m, b)
}
func (m *GetOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerRequest.Marshal(b, m, deterministic)
}
func (dst *GetOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerRequest.Merge(dst, src)
}
func (m *GetOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_GetOwnerRequest.Size(m)
}
func (m *GetOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerRequest proto.InternalMessageInfo

func (m *GetOwnerRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetOwnerResponse struct {
	OwnerUid             string   `protobuf:"bytes,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerResponse) Reset()         { *m = GetOwnerResponse{} }
func (m *GetOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*GetOwnerResponse) ProtoMessage()    {}
func (*GetOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_post_1d90b6a40872f3d1, []int{14}
}
func (m *GetOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerResponse.Unmarshal(m, b)
}
func (m *GetOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerResponse.Marshal(b, m, deterministic)
}
func (dst *GetOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerResponse.Merge(dst, src)
}
func (m *GetOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_GetOwnerResponse.Size(m)
}
func (m *GetOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerResponse proto.InternalMessageInfo

func (m *GetOwnerResponse) GetOwnerUid() string {
	if m != nil {
		return m.OwnerUid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListPostsRequest)(nil), "post.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "post.ListPostsResponse")
	proto.RegisterType((*GetPostRequest)(nil), "post.GetPostRequest")
	proto.RegisterType((*SinglePost)(nil), "post.SinglePost")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*UpdatePostRequest)(nil), "post.UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "post.UpdatePostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "post.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "post.DeletePostResponse")
	proto.RegisterType((*CheckExistsRequest)(nil), "post.CheckExistsRequest")
	proto.RegisterType((*CheckExistsResponse)(nil), "post.CheckExistsResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "post.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "post.GetTokenResponse")
	proto.RegisterType((*GetOwnerRequest)(nil), "post.GetOwnerRequest")
	proto.RegisterType((*GetOwnerResponse)(nil), "post.GetOwnerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*SinglePost, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*SinglePost, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	CheckExists(ctx context.Context, in *CheckExistsRequest, opts ...grpc.CallOption) (*CheckExistsResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	GetOwner(ctx context.Context, in *GetOwnerRequest, opts ...grpc.CallOption) (*GetOwnerResponse, error)
}

type postClient struct {
	cc *grpc.ClientConn
}

func NewPostClient(cc *grpc.ClientConn) PostClient {
	return &postClient{cc}
}

func (c *postClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/post.Post/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*SinglePost, error) {
	out := new(SinglePost)
	err := c.cc.Invoke(ctx, "/post.Post/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*SinglePost, error) {
	out := new(SinglePost)
	err := c.cc.Invoke(ctx, "/post.Post/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/post.Post/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/post.Post/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) CheckExists(ctx context.Context, in *CheckExistsRequest, opts ...grpc.CallOption) (*CheckExistsResponse, error) {
	out := new(CheckExistsResponse)
	err := c.cc.Invoke(ctx, "/post.Post/CheckExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/post.Post/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetOwner(ctx context.Context, in *GetOwnerRequest, opts ...grpc.CallOption) (*GetOwnerResponse, error) {
	out := new(GetOwnerResponse)
	err := c.cc.Invoke(ctx, "/post.Post/GetOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	GetPost(context.Context, *GetPostRequest) (*SinglePost, error)
	CreatePost(context.Context, *CreatePostRequest) (*SinglePost, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	CheckExists(context.Context, *CheckExistsRequest) (*CheckExistsResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	GetOwner(context.Context, *GetOwnerRequest) (*GetOwnerResponse, error)
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_CheckExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).CheckExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/CheckExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CheckExists(ctx, req.(*CheckExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Post/GetOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetOwner(ctx, req.(*GetOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPosts",
			Handler:    _Post_ListPosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _Post_GetPost_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _Post_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _Post_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Post_DeletePost_Handler,
		},
		{
			MethodName: "CheckExists",
			Handler:    _Post_CheckExists_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Post_GetToken_Handler,
		},
		{
			MethodName: "GetOwner",
			Handler:    _Post_GetOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/post/proto/post.proto",
}

func init() {
	proto.RegisterFile("services/post/proto/post.proto", fileDescriptor_post_1d90b6a40872f3d1)
}

var fileDescriptor_post_1d90b6a40872f3d1 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x6d, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0x5f, 0xd7, 0x5c, 0x25, 0x68, 0x4d, 0x29, 0x21, 0x42, 0xa3, 0x32, 0xd2, 0xd4, 0x2f,
	0xa4, 0xa2, 0x7c, 0xe0, 0x55, 0x9a, 0x60, 0x4c, 0x13, 0x12, 0x1a, 0x28, 0x5d, 0x7f, 0x40, 0x5f,
	0x6e, 0xc5, 0x6a, 0xda, 0x84, 0xd8, 0x65, 0x88, 0x1f, 0xca, 0xaf, 0xe0, 0x47, 0xa0, 0x38, 0x4e,
	0xec, 0xcc, 0x05, 0xa6, 0x7d, 0xf3, 0x9d, 0xef, 0x9e, 0xe7, 0xee, 0xfc, 0x9c, 0xe1, 0x90, 0x63,
	0xf2, 0x9d, 0x2d, 0x90, 0x8f, 0xe2, 0x88, 0x8b, 0x51, 0x9c, 0x44, 0x22, 0x92, 0x47, 0x5f, 0x1e,
	0x49, 0x3d, 0x3d, 0x7b, 0x8f, 0x57, 0x51, 0xb4, 0x0a, 0x31, 0xbb, 0x9e, 0xef, 0x2e, 0x47, 0x82,
	0x6d, 0x90, 0x8b, 0xd9, 0x26, 0xce, 0xc2, 0xe8, 0x39, 0x74, 0x3e, 0x31, 0x2e, 0xbe, 0x44, 0x5c,
	0xf0, 0x00, 0xbf, 0xed, 0x90, 0x0b, 0xe2, 0x41, 0x2b, 0x9e, 0xad, 0x70, 0xc2, 0x7e, 0xa2, 0x5b,
	0x19, 0x54, 0x86, 0x8d, 0xa0, 0xb0, 0xc9, 0x21, 0x40, 0x7a, 0x3e, 0xdf, 0x6d, 0xe6, 0x98, 0xb8,
	0x55, 0x79, 0x6b, 0x78, 0xe8, 0x15, 0x74, 0x0d, 0x3c, 0x1e, 0x47, 0x5b, 0x8e, 0xe4, 0x08, 0x1a,
	0x69, 0x35, 0xdc, 0xad, 0x0c, 0x6a, 0xc3, 0xf6, 0xb8, 0xe3, 0xcb, 0x3a, 0x27, 0x6c, 0xbb, 0x0a,
	0x31, 0x8d, 0x0c, 0xb2, 0xeb, 0x12, 0x71, 0xf5, 0x9f, 0xc4, 0x35, 0x8b, 0x98, 0xc2, 0x9d, 0x33,
	0x94, 0xbc, 0x79, 0x1b, 0x1d, 0xa8, 0xed, 0xd8, 0x52, 0x76, 0xe0, 0x04, 0xe9, 0x91, 0xfe, 0xaa,
	0x00, 0x68, 0x56, 0x3b, 0x80, 0xb8, 0x70, 0xb0, 0xe3, 0x98, 0x4c, 0xd9, 0x52, 0xf2, 0x3b, 0x41,
	0x6e, 0x92, 0x1e, 0x34, 0x04, 0x13, 0x21, 0x4a, 0x66, 0x27, 0xc8, 0x0c, 0x89, 0x90, 0x84, 0x6e,
	0x5d, 0x21, 0x24, 0x21, 0x79, 0x09, 0xce, 0x22, 0xc1, 0x99, 0xc0, 0xe5, 0x3b, 0xe1, 0x36, 0x06,
	0x95, 0x61, 0x7b, 0xec, 0xf9, 0xd9, 0x23, 0xf8, 0xf9, 0x23, 0xf8, 0x17, 0xf9, 0x23, 0x04, 0x3a,
	0x98, 0xbc, 0x06, 0xd8, 0x44, 0x4b, 0x76, 0xc9, 0x64, 0x6a, 0xf3, 0xbf, 0xa9, 0x46, 0x34, 0x5d,
	0x43, 0xf7, 0x44, 0x02, 0x99, 0xfd, 0xa7, 0x25, 0x47, 0x6b, 0xdc, 0xaa, 0x06, 0x33, 0x43, 0x37,
	0x52, 0xdd, 0xd3, 0x48, 0x4d, 0x37, 0x62, 0x8c, 0xa2, 0x5e, 0x1a, 0x05, 0x5d, 0x40, 0x77, 0x1a,
	0x2f, 0x6f, 0x44, 0xa6, 0x26, 0x5c, 0xd5, 0x13, 0xbe, 0xe1, 0x1c, 0x69, 0x0f, 0x88, 0x49, 0x92,
	0x09, 0x89, 0xbe, 0x81, 0xee, 0x07, 0x0c, 0xf1, 0x56, 0xd4, 0x29, 0xa4, 0x99, 0xac, 0x20, 0x8f,
	0x80, 0x9c, 0x7c, 0xc5, 0xc5, 0xfa, 0xf4, 0x07, 0x33, 0x56, 0xc0, 0xd6, 0xce, 0x53, 0xb8, 0x57,
	0x8a, 0x53, 0xd2, 0xee, 0x43, 0x13, 0xa5, 0x47, 0xc6, 0xb6, 0x02, 0x65, 0xd1, 0x53, 0xb8, 0x7b,
	0x86, 0xe2, 0x22, 0x2d, 0xc5, 0xa8, 0x73, 0x16, 0xc7, 0x1f, 0x73, 0xd4, 0xcc, 0x20, 0x8f, 0xc0,
	0x99, 0xc5, 0xf1, 0x04, 0x17, 0x09, 0x0a, 0x55, 0xad, 0x76, 0xd0, 0x21, 0x74, 0x34, 0x8c, 0xa2,
	0xdc, 0xdb, 0x2f, 0x7d, 0x22, 0x09, 0x3f, 0x5f, 0x6d, 0x31, 0xf9, 0x7b, 0x13, 0xbe, 0x84, 0x53,
	0x41, 0x0a, 0xce, 0x83, 0x56, 0x94, 0x3a, 0xa6, 0x45, 0x68, 0x61, 0x8f, 0x7f, 0xd7, 0xa0, 0x2e,
	0x57, 0xe5, 0x2d, 0x38, 0xc5, 0x5a, 0x93, 0x7e, 0xb6, 0xbf, 0xd7, 0xff, 0x0d, 0xef, 0x81, 0xe5,
	0x57, 0x14, 0xcf, 0xe0, 0x40, 0xed, 0x26, 0xe9, 0x65, 0x31, 0xe5, 0x55, 0xf5, 0xac, 0x1f, 0x81,
	0xbc, 0x00, 0xd0, 0x8a, 0x26, 0x0a, 0xd9, 0xd2, 0xf8, 0x9e, 0xc4, 0x63, 0x00, 0x2d, 0x9c, 0x3c,
	0xd1, 0xd2, 0xab, 0xe7, 0xda, 0x17, 0xaa, 0xd8, 0x63, 0x00, 0x2d, 0x93, 0x1c, 0xc0, 0x52, 0x5d,
	0x0e, 0x60, 0x2b, 0x8a, 0xbc, 0x87, 0xb6, 0xa1, 0x14, 0xa2, 0x02, 0x6d, 0x91, 0x79, 0x0f, 0xf7,
	0xdc, 0x28, 0x8c, 0x57, 0xd0, 0xca, 0xdf, 0x9d, 0xdc, 0x2f, 0x46, 0x66, 0xca, 0xc9, 0xeb, 0x5f,
	0x77, 0x97, 0x52, 0xe5, 0x1b, 0x1b, 0xa9, 0xa6, 0x30, 0x8c, 0xd4, 0x92, 0x14, 0xe6, 0x4d, 0xf9,
	0xcd, 0x3c, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x01, 0xbe, 0x5c, 0x5c, 0x06, 0x00, 0x00,
}
