// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/user/proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserInfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{0}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *UpdateUserRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *UpdateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{4}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type DeleteUserRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{5}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *DeleteUserRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *DeleteUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{6}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type GetServiceTokenRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceTokenRequest) Reset()         { *m = GetServiceTokenRequest{} }
func (m *GetServiceTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceTokenRequest) ProtoMessage()    {}
func (*GetServiceTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{7}
}

func (m *GetServiceTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceTokenRequest.Unmarshal(m, b)
}
func (m *GetServiceTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceTokenRequest.Merge(m, src)
}
func (m *GetServiceTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceTokenRequest.Size(m)
}
func (m *GetServiceTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceTokenRequest proto.InternalMessageInfo

func (m *GetServiceTokenRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetServiceTokenRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type GetServiceTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceTokenResponse) Reset()         { *m = GetServiceTokenResponse{} }
func (m *GetServiceTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceTokenResponse) ProtoMessage()    {}
func (*GetServiceTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{8}
}

func (m *GetServiceTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceTokenResponse.Unmarshal(m, b)
}
func (m *GetServiceTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceTokenResponse.Merge(m, src)
}
func (m *GetServiceTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceTokenResponse.Size(m)
}
func (m *GetServiceTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceTokenResponse proto.InternalMessageInfo

func (m *GetServiceTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserTokenRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserTokenRequest) Reset()         { *m = GetUserTokenRequest{} }
func (m *GetUserTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserTokenRequest) ProtoMessage()    {}
func (*GetUserTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{9}
}

func (m *GetUserTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserTokenRequest.Unmarshal(m, b)
}
func (m *GetUserTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetUserTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserTokenRequest.Merge(m, src)
}
func (m *GetUserTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserTokenRequest.Size(m)
}
func (m *GetUserTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserTokenRequest proto.InternalMessageInfo

func (m *GetUserTokenRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *GetUserTokenRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetUserTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserTokenResponse) Reset()         { *m = GetUserTokenResponse{} }
func (m *GetUserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserTokenResponse) ProtoMessage()    {}
func (*GetUserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{10}
}

func (m *GetUserTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserTokenResponse.Unmarshal(m, b)
}
func (m *GetUserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetUserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserTokenResponse.Merge(m, src)
}
func (m *GetUserTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserTokenResponse.Size(m)
}
func (m *GetUserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserTokenResponse proto.InternalMessageInfo

func (m *GetUserTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserByTokenRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByTokenRequest) Reset()         { *m = GetUserByTokenRequest{} }
func (m *GetUserByTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByTokenRequest) ProtoMessage()    {}
func (*GetUserByTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{11}
}

func (m *GetUserByTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByTokenRequest.Unmarshal(m, b)
}
func (m *GetUserByTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByTokenRequest.Merge(m, src)
}
func (m *GetUserByTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByTokenRequest.Size(m)
}
func (m *GetUserByTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByTokenRequest proto.InternalMessageInfo

func (m *GetUserByTokenRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *GetUserByTokenRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

type GetUserByTokenResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByTokenResponse) Reset()         { *m = GetUserByTokenResponse{} }
func (m *GetUserByTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByTokenResponse) ProtoMessage()    {}
func (*GetUserByTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{12}
}

func (m *GetUserByTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByTokenResponse.Unmarshal(m, b)
}
func (m *GetUserByTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByTokenResponse.Merge(m, src)
}
func (m *GetUserByTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByTokenResponse.Size(m)
}
func (m *GetUserByTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByTokenResponse proto.InternalMessageInfo

func (m *GetUserByTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserInfoRequest)(nil), "user.GetUserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "user.DeleteUserResponse")
	proto.RegisterType((*GetServiceTokenRequest)(nil), "user.GetServiceTokenRequest")
	proto.RegisterType((*GetServiceTokenResponse)(nil), "user.GetServiceTokenResponse")
	proto.RegisterType((*GetUserTokenRequest)(nil), "user.GetUserTokenRequest")
	proto.RegisterType((*GetUserTokenResponse)(nil), "user.GetUserTokenResponse")
	proto.RegisterType((*GetUserByTokenRequest)(nil), "user.GetUserByTokenRequest")
	proto.RegisterType((*GetUserByTokenResponse)(nil), "user.GetUserByTokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetServiceToken(ctx context.Context, in *GetServiceTokenRequest, opts ...grpc.CallOption) (*GetServiceTokenResponse, error)
	GetUserToken(ctx context.Context, in *GetUserTokenRequest, opts ...grpc.CallOption) (*GetUserTokenResponse, error)
	GetUserByToken(ctx context.Context, in *GetUserByTokenRequest, opts ...grpc.CallOption) (*GetUserByTokenResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.user/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/user.user/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetServiceToken(ctx context.Context, in *GetServiceTokenRequest, opts ...grpc.CallOption) (*GetServiceTokenResponse, error) {
	out := new(GetServiceTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetServiceToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserToken(ctx context.Context, in *GetUserTokenRequest, opts ...grpc.CallOption) (*GetUserTokenResponse, error) {
	out := new(GetUserTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetUserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserByToken(ctx context.Context, in *GetUserByTokenRequest, opts ...grpc.CallOption) (*GetUserByTokenResponse, error) {
	out := new(GetUserByTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetUserByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUserInfo(context.Context, *GetUserInfoRequest) (*UserInfo, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserInfo, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetServiceToken(context.Context, *GetServiceTokenRequest) (*GetServiceTokenResponse, error)
	GetUserToken(context.Context, *GetUserTokenRequest) (*GetUserTokenResponse, error)
	GetUserByToken(context.Context, *GetUserByTokenRequest) (*GetUserByTokenResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetServiceToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetServiceToken(ctx, req.(*GetServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserToken(ctx, req.(*GetUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByToken(ctx, req.(*GetUserByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _User_DeleteUser_Handler,
		},
		{
			MethodName: "GetServiceToken",
			Handler:    _User_GetServiceToken_Handler,
		},
		{
			MethodName: "GetUserToken",
			Handler:    _User_GetUserToken_Handler,
		},
		{
			MethodName: "GetUserByToken",
			Handler:    _User_GetUserByToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/user/proto/user.proto",
}

func init() { proto.RegisterFile("services/user/proto/user.proto", fileDescriptor_5f65f38375cad887) }

var fileDescriptor_5f65f38375cad887 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0x25, 0x71, 0x36, 0x92, 0xbb, 0x91, 0x2d, 0x5a, 0xb6, 0x78, 0x5e, 0x36, 0x86, 0x1e, 0xc6,
	0x18, 0x23, 0x81, 0x8d, 0xb1, 0xbd, 0x05, 0xb6, 0x95, 0x10, 0x5a, 0x0a, 0x4d, 0x9a, 0xe7, 0xe0,
	0x26, 0xb7, 0x10, 0xda, 0xda, 0xaa, 0xe5, 0xb4, 0x94, 0xfe, 0xd5, 0xfe, 0x98, 0xa2, 0x2f, 0xdb,
	0xb2, 0x5c, 0xd3, 0x97, 0xbe, 0xe9, 0xfa, 0x48, 0xe7, 0xe8, 0xea, 0x9e, 0x63, 0xf8, 0xc4, 0x31,
	0xb9, 0xda, 0xae, 0x91, 0x8f, 0x77, 0x1c, 0x93, 0x31, 0x4b, 0xe2, 0x34, 0x96, 0xcb, 0x91, 0x5c,
	0x92, 0x96, 0x58, 0xd3, 0x2f, 0x40, 0xa6, 0x98, 0x2e, 0x39, 0x26, 0xb3, 0xe8, 0x34, 0x9e, 0xe3,
	0xe5, 0x0e, 0x79, 0x4a, 0x5e, 0x83, 0xb7, 0xdb, 0x6e, 0xfc, 0xc6, 0xe7, 0xc6, 0xd7, 0xce, 0x5c,
	0x2c, 0xe9, 0x1f, 0x68, 0x9b, 0x4d, 0x2e, 0x4a, 0x02, 0x68, 0x0b, 0xb6, 0x28, 0xbc, 0x40, 0xbf,
	0x29, 0x3f, 0x67, 0x35, 0x0d, 0xa1, 0xf7, 0x2f, 0xc1, 0x30, 0x45, 0x71, 0xde, 0x08, 0xf4, 0xe1,
	0x59, 0x1a, 0x9f, 0x61, 0xa4, 0x49, 0x54, 0x51, 0x47, 0x23, 0x30, 0x16, 0x72, 0x7e, 0x1d, 0x27,
	0x1b, 0xdf, 0x53, 0x98, 0xa9, 0xe9, 0x2d, 0xf4, 0x96, 0x6c, 0x53, 0x92, 0x08, 0xa0, 0x1d, 0xb2,
	0xed, 0x71, 0x41, 0x25, 0xab, 0xc9, 0x10, 0x3a, 0x82, 0x58, 0x81, 0x4a, 0x29, 0xff, 0x60, 0xfa,
	0xf3, 0xac, 0xfe, 0x32, 0xf1, 0x56, 0x49, 0xbc, 0x0f, 0xa4, 0x28, 0xce, 0x59, 0x1c, 0x71, 0xa4,
	0x2b, 0xe8, 0xfd, 0xc7, 0x73, 0x7c, 0xb2, 0x2b, 0x09, 0xd9, 0xa2, 0x80, 0x96, 0x3d, 0x80, 0x77,
	0x53, 0x4c, 0x17, 0x6a, 0xf2, 0xf2, 0x68, 0xe1, 0xc5, 0x43, 0xc6, 0x66, 0x66, 0x6c, 0xaa, 0x10,
	0xaa, 0x21, 0x63, 0x0b, 0x5c, 0x27, 0x98, 0x1a, 0xd5, 0xec, 0x03, 0x1d, 0xc3, 0xc0, 0x61, 0x53,
	0x42, 0xd5, 0x03, 0xa4, 0x2b, 0x78, 0xa3, 0xdd, 0x64, 0x69, 0xd7, 0xf5, 0xad, 0x3b, 0x6b, 0x56,
	0x3f, 0x76, 0x79, 0xd2, 0xdf, 0xa1, 0x6f, 0x0b, 0xd4, 0x5e, 0xe7, 0x08, 0xde, 0xea, 0xdd, 0x7f,
	0x6f, 0x1e, 0x7d, 0xa1, 0xda, 0x41, 0xd0, 0x6f, 0xf2, 0x81, 0x2d, 0x4a, 0x7d, 0x05, 0x27, 0x15,
	0x3f, 0xee, 0x3c, 0x90, 0x21, 0x23, 0xbf, 0xe1, 0x45, 0x21, 0x64, 0xc4, 0x1f, 0xc9, 0x18, 0xba,
	0xb9, 0x0b, 0xba, 0x0a, 0xc9, 0x76, 0xfe, 0x02, 0xc8, 0xb3, 0x43, 0x06, 0x0a, 0x75, 0xd2, 0xe4,
	0x1c, 0x9b, 0x00, 0xe4, 0x96, 0x34, 0xc7, 0x9c, 0x84, 0x04, 0xbe, 0x0b, 0xe8, 0x5e, 0x26, 0x00,
	0xb9, 0xb9, 0x0c, 0x81, 0xe3, 0x67, 0x43, 0xe0, 0xfa, 0x90, 0x1c, 0xc2, 0xab, 0x92, 0x73, 0xc8,
	0x30, 0xeb, 0xba, 0xc2, 0x9e, 0xc1, 0xc7, 0x07, 0x50, 0xcd, 0xb7, 0x07, 0x2f, 0x8b, 0x73, 0x27,
	0xef, 0xad, 0x27, 0xb4, 0x98, 0x82, 0x2a, 0x48, 0xd3, 0xec, 0x43, 0xd7, 0x9e, 0x1e, 0xf9, 0x60,
	0xed, 0xb6, 0x6d, 0x12, 0x0c, 0xab, 0x41, 0x45, 0x76, 0xf2, 0x5c, 0xfe, 0x47, 0x7f, 0xde, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xed, 0x62, 0xbe, 0x1a, 0x69, 0x05, 0x00, 0x00,
}
