// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/user/proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserInfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{0}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *UpdateUserRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *UpdateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{4}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type DeleteUserRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{5}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *DeleteUserRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *DeleteUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{6}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type GetServiceTokenRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceTokenRequest) Reset()         { *m = GetServiceTokenRequest{} }
func (m *GetServiceTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceTokenRequest) ProtoMessage()    {}
func (*GetServiceTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{7}
}

func (m *GetServiceTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceTokenRequest.Unmarshal(m, b)
}
func (m *GetServiceTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceTokenRequest.Merge(m, src)
}
func (m *GetServiceTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceTokenRequest.Size(m)
}
func (m *GetServiceTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceTokenRequest proto.InternalMessageInfo

func (m *GetServiceTokenRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetServiceTokenRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type GetServiceTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceTokenResponse) Reset()         { *m = GetServiceTokenResponse{} }
func (m *GetServiceTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceTokenResponse) ProtoMessage()    {}
func (*GetServiceTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{8}
}

func (m *GetServiceTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceTokenResponse.Unmarshal(m, b)
}
func (m *GetServiceTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceTokenResponse.Merge(m, src)
}
func (m *GetServiceTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceTokenResponse.Size(m)
}
func (m *GetServiceTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceTokenResponse proto.InternalMessageInfo

func (m *GetServiceTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetTokenRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{9}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *GetTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetAccessTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenResponse) Reset()         { *m = GetAccessTokenResponse{} }
func (m *GetAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenResponse) ProtoMessage()    {}
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{10}
}

func (m *GetAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenResponse.Merge(m, src)
}
func (m *GetAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenResponse.Size(m)
}
func (m *GetAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenResponse proto.InternalMessageInfo

func (m *GetAccessTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetAccessTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetUserByAccessTokenRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	UserToken            string   `protobuf:"bytes,2,opt,name=userToken,proto3" json:"userToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByAccessTokenRequest) Reset()         { *m = GetUserByAccessTokenRequest{} }
func (m *GetUserByAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccessTokenRequest) ProtoMessage()    {}
func (*GetUserByAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{11}
}

func (m *GetUserByAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetUserByAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccessTokenRequest.Merge(m, src)
}
func (m *GetUserByAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccessTokenRequest.Size(m)
}
func (m *GetUserByAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccessTokenRequest proto.InternalMessageInfo

func (m *GetUserByAccessTokenRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *GetUserByAccessTokenRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

type GetUserByAccessTokenResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByAccessTokenResponse) Reset()         { *m = GetUserByAccessTokenResponse{} }
func (m *GetUserByAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccessTokenResponse) ProtoMessage()    {}
func (*GetUserByAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{12}
}

func (m *GetUserByAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetUserByAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccessTokenResponse.Merge(m, src)
}
func (m *GetUserByAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccessTokenResponse.Size(m)
}
func (m *GetUserByAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccessTokenResponse proto.InternalMessageInfo

func (m *GetUserByAccessTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetRefreshTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefreshTokenResponse) Reset()         { *m = GetRefreshTokenResponse{} }
func (m *GetRefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetRefreshTokenResponse) ProtoMessage()    {}
func (*GetRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{13}
}

func (m *GetRefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefreshTokenResponse.Unmarshal(m, b)
}
func (m *GetRefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetRefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefreshTokenResponse.Merge(m, src)
}
func (m *GetRefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetRefreshTokenResponse.Size(m)
}
func (m *GetRefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefreshTokenResponse proto.InternalMessageInfo

func (m *GetRefreshTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshAccessTokenRequest struct {
	ApiToken             string   `protobuf:"bytes,1,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenRequest) Reset()         { *m = RefreshAccessTokenRequest{} }
func (m *RefreshAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenRequest) ProtoMessage()    {}
func (*RefreshAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{14}
}

func (m *RefreshAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenRequest.Unmarshal(m, b)
}
func (m *RefreshAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenRequest.Merge(m, src)
}
func (m *RefreshAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenRequest.Size(m)
}
func (m *RefreshAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenRequest proto.InternalMessageInfo

func (m *RefreshAccessTokenRequest) GetApiToken() string {
	if m != nil {
		return m.ApiToken
	}
	return ""
}

func (m *RefreshAccessTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshAccessTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenResponse) Reset()         { *m = RefreshAccessTokenResponse{} }
func (m *RefreshAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenResponse) ProtoMessage()    {}
func (*RefreshAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f65f38375cad887, []int{15}
}

func (m *RefreshAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenResponse.Unmarshal(m, b)
}
func (m *RefreshAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenResponse.Merge(m, src)
}
func (m *RefreshAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenResponse.Size(m)
}
func (m *RefreshAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenResponse proto.InternalMessageInfo

func (m *RefreshAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshAccessTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserInfoRequest)(nil), "user.GetUserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "user.DeleteUserResponse")
	proto.RegisterType((*GetServiceTokenRequest)(nil), "user.GetServiceTokenRequest")
	proto.RegisterType((*GetServiceTokenResponse)(nil), "user.GetServiceTokenResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "user.GetTokenRequest")
	proto.RegisterType((*GetAccessTokenResponse)(nil), "user.GetAccessTokenResponse")
	proto.RegisterType((*GetUserByAccessTokenRequest)(nil), "user.GetUserByAccessTokenRequest")
	proto.RegisterType((*GetUserByAccessTokenResponse)(nil), "user.GetUserByAccessTokenResponse")
	proto.RegisterType((*GetRefreshTokenResponse)(nil), "user.GetRefreshTokenResponse")
	proto.RegisterType((*RefreshAccessTokenRequest)(nil), "user.RefreshAccessTokenRequest")
	proto.RegisterType((*RefreshAccessTokenResponse)(nil), "user.RefreshAccessTokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetServiceToken(ctx context.Context, in *GetServiceTokenRequest, opts ...grpc.CallOption) (*GetServiceTokenResponse, error)
	GetAccessToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error)
	GetRefreshToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetRefreshTokenResponse, error)
	RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*RefreshAccessTokenResponse, error)
	GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...grpc.CallOption) (*GetUserByAccessTokenResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.user/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/user.user/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetServiceToken(ctx context.Context, in *GetServiceTokenRequest, opts ...grpc.CallOption) (*GetServiceTokenResponse, error) {
	out := new(GetServiceTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetServiceToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAccessToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error) {
	out := new(GetAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetRefreshToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetRefreshTokenResponse, error) {
	out := new(GetRefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetRefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*RefreshAccessTokenResponse, error) {
	out := new(RefreshAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/RefreshAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...grpc.CallOption) (*GetUserByAccessTokenResponse, error) {
	out := new(GetUserByAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetUserByAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUserInfo(context.Context, *GetUserInfoRequest) (*UserInfo, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserInfo, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetServiceToken(context.Context, *GetServiceTokenRequest) (*GetServiceTokenResponse, error)
	GetAccessToken(context.Context, *GetTokenRequest) (*GetAccessTokenResponse, error)
	GetRefreshToken(context.Context, *GetTokenRequest) (*GetRefreshTokenResponse, error)
	RefreshAccessToken(context.Context, *RefreshAccessTokenRequest) (*RefreshAccessTokenResponse, error)
	GetUserByAccessToken(context.Context, *GetUserByAccessTokenRequest) (*GetUserByAccessTokenResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetServiceToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetServiceToken(ctx, req.(*GetServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAccessToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetRefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetRefreshToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/RefreshAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RefreshAccessToken(ctx, req.(*RefreshAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserByAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserByAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByAccessToken(ctx, req.(*GetUserByAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _User_DeleteUser_Handler,
		},
		{
			MethodName: "GetServiceToken",
			Handler:    _User_GetServiceToken_Handler,
		},
		{
			MethodName: "GetAccessToken",
			Handler:    _User_GetAccessToken_Handler,
		},
		{
			MethodName: "GetRefreshToken",
			Handler:    _User_GetRefreshToken_Handler,
		},
		{
			MethodName: "RefreshAccessToken",
			Handler:    _User_RefreshAccessToken_Handler,
		},
		{
			MethodName: "GetUserByAccessToken",
			Handler:    _User_GetUserByAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/user/proto/user.proto",
}

func init() { proto.RegisterFile("services/user/proto/user.proto", fileDescriptor_5f65f38375cad887) }

var fileDescriptor_5f65f38375cad887 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x55, 0x9b, 0x16, 0xa5, 0xaf, 0xa8, 0x10, 0x2b, 0xd0, 0x65, 0x09, 0x10, 0x7c, 0x40, 0x9c,
	0x1a, 0x04, 0x42, 0x70, 0x2b, 0x9f, 0x8a, 0x2a, 0x21, 0x0e, 0x29, 0x55, 0x0f, 0x08, 0xa1, 0x6d,
	0x32, 0x15, 0x11, 0x90, 0x35, 0xf6, 0x06, 0x84, 0xf8, 0x13, 0xfc, 0x64, 0xb4, 0xfe, 0xd8, 0xf5,
	0xc6, 0x4e, 0x14, 0x40, 0xbd, 0xad, 0x67, 0x3c, 0xef, 0xcd, 0x78, 0xe6, 0xcd, 0xe2, 0xb6, 0x22,
	0xf9, 0x7d, 0x3a, 0x26, 0x35, 0x98, 0x2b, 0x92, 0x03, 0x21, 0xf3, 0x22, 0xd7, 0x9f, 0x07, 0xfa,
	0x93, 0x6d, 0x95, 0xdf, 0xfc, 0x1e, 0xd8, 0x90, 0x8a, 0x13, 0x45, 0xf2, 0x68, 0x76, 0x9e, 0x8f,
	0xe8, 0xdb, 0x9c, 0x54, 0xc1, 0xae, 0xa2, 0x35, 0x9f, 0x4e, 0x92, 0x8d, 0xfe, 0xc6, 0xfd, 0x9d,
	0x51, 0xf9, 0xc9, 0x9f, 0xa2, 0xed, 0x2e, 0x85, 0x5e, 0x96, 0xa2, 0x5d, 0xa2, 0xcd, 0xb2, 0xaf,
	0x94, 0x6c, 0x6a, 0x73, 0x75, 0xe6, 0x19, 0x3a, 0x2f, 0x25, 0x65, 0x05, 0x95, 0xf1, 0x8e, 0xa0,
	0x8b, 0xed, 0x22, 0xff, 0x4c, 0x33, 0x0b, 0x62, 0x0e, 0xab, 0x60, 0x4a, 0x9f, 0xc8, 0x94, 0xfa,
	0x91, 0xcb, 0x49, 0xd2, 0x32, 0x3e, 0x77, 0xe6, 0xbf, 0xd0, 0x39, 0x11, 0x93, 0x05, 0x8a, 0x14,
	0xed, 0x4c, 0x4c, 0xdf, 0x79, 0x2c, 0xd5, 0x99, 0xf5, 0xb0, 0x53, 0x02, 0x1b, 0xa7, 0x61, 0xaa,
	0x0d, 0xae, 0xbe, 0x56, 0xa3, 0xbe, 0x8a, 0x7c, 0x6b, 0x81, 0xbc, 0x0b, 0xe6, 0x93, 0x2b, 0x91,
	0xcf, 0x14, 0xf1, 0x8f, 0xe8, 0xbc, 0xa2, 0x2f, 0x74, 0x61, 0x29, 0x95, 0xb4, 0x3e, 0x81, 0xa5,
	0x7d, 0x83, 0xeb, 0x43, 0x2a, 0x8e, 0x4d, 0xe7, 0x75, 0xa8, 0xf7, 0xe2, 0x99, 0x10, 0x47, 0xae,
	0x6d, 0xe6, 0x50, 0xb2, 0x66, 0x42, 0x1c, 0xd3, 0x58, 0x52, 0xe1, 0x58, 0x2b, 0x03, 0x1f, 0x60,
	0x3f, 0x40, 0x33, 0x44, 0xf1, 0x06, 0x72, 0xc2, 0x95, 0x21, 0x15, 0x0d, 0xde, 0x55, 0x35, 0xff,
	0x6b, 0xbf, 0x9f, 0xe9, 0x2a, 0x9f, 0x8f, 0xc7, 0xa4, 0xd4, 0x1a, 0x69, 0xb9, 0xd7, 0xdb, 0xac,
	0x5f, 0xef, 0x14, 0x37, 0xed, 0xd8, 0xbf, 0xf8, 0xd9, 0xc0, 0xf9, 0xcf, 0x46, 0xf1, 0x07, 0xe8,
	0xc5, 0x81, 0x6d, 0x82, 0xa1, 0xb2, 0xcc, 0x23, 0x8f, 0xe8, 0x5c, 0x92, 0xfa, 0xb4, 0xce, 0x23,
	0xbf, 0xc7, 0x0d, 0x7b, 0xfb, 0x2f, 0x33, 0xe7, 0xb8, 0x2c, 0x3d, 0x1a, 0x9b, 0x7c, 0xc3, 0xc6,
	0xcf, 0x90, 0xc6, 0xc0, 0x6d, 0x42, 0x7d, 0xec, 0x66, 0xb5, 0xd9, 0x12, 0xf8, 0xa6, 0x75, 0x38,
	0x1e, 0xfe, 0xde, 0x86, 0x5e, 0x3e, 0xec, 0x09, 0x76, 0xbd, 0xe5, 0xc3, 0x92, 0x03, 0xbd, 0x9e,
	0xc2, 0x7d, 0x94, 0xee, 0x19, 0x4f, 0x75, 0xf3, 0x31, 0x50, 0xef, 0x14, 0xb6, 0x6f, 0xbc, 0xc1,
	0x96, 0x09, 0xc2, 0x0e, 0x81, 0x5a, 0xaa, 0x2e, 0x2c, 0xd8, 0x1c, 0x69, 0x12, 0x3a, 0x6c, 0xfd,
	0x87, 0x40, 0x2d, 0x3a, 0x07, 0x10, 0xe8, 0xdc, 0x01, 0x84, 0xfa, 0x64, 0x6f, 0xb5, 0x40, 0x7c,
	0x45, 0xb1, 0x5e, 0x55, 0x75, 0x44, 0xb6, 0xe9, 0xad, 0x25, 0x5e, 0x8b, 0xf7, 0x1a, 0x7b, 0x4d,
	0x25, 0xb0, 0x6b, 0x55, 0x40, 0x03, 0xa7, 0x66, 0x89, 0xf5, 0x75, 0xa8, 0xd3, 0xf2, 0x67, 0x70,
	0x19, 0x4e, 0x9d, 0x4f, 0x74, 0x62, 0x4f, 0xc1, 0xc2, 0xf1, 0x61, 0x77, 0x4c, 0xd0, 0xd2, 0xa9,
	0x4d, 0xfb, 0xcb, 0x2f, 0x58, 0xe0, 0x0f, 0xe8, 0xc6, 0x74, 0xc5, 0xee, 0x36, 0x66, 0x26, 0x26,
	0xe6, 0x94, 0xaf, 0xba, 0x62, 0xe0, 0xcf, 0x2e, 0xe9, 0x7f, 0xe2, 0xa3, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xda, 0x21, 0x20, 0x54, 0x35, 0x07, 0x00, 0x00,
}
