// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/comment/proto/comment.proto

package comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCommentsRequest struct {
	PostUid              string   `protobuf:"bytes,1,opt,name=postUid,proto3" json:"postUid,omitempty"`
	CommentUid           string   `protobuf:"bytes,2,opt,name=commentUid,proto3" json:"commentUid,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,4,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommentsRequest) Reset()         { *m = ListCommentsRequest{} }
func (m *ListCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCommentsRequest) ProtoMessage()    {}
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{0}
}

func (m *ListCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsRequest.Unmarshal(m, b)
}
func (m *ListCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsRequest.Marshal(b, m, deterministic)
}
func (m *ListCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsRequest.Merge(m, src)
}
func (m *ListCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCommentsRequest.Size(m)
}
func (m *ListCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsRequest proto.InternalMessageInfo

func (m *ListCommentsRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *ListCommentsRequest) GetCommentUid() string {
	if m != nil {
		return m.CommentUid
	}
	return ""
}

func (m *ListCommentsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCommentsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListCommentsResponse struct {
	Comments             []*SingleComment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	PageSize             int32            `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32            `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCommentsResponse) Reset()         { *m = ListCommentsResponse{} }
func (m *ListCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCommentsResponse) ProtoMessage()    {}
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{1}
}

func (m *ListCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommentsResponse.Unmarshal(m, b)
}
func (m *ListCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommentsResponse.Marshal(b, m, deterministic)
}
func (m *ListCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommentsResponse.Merge(m, src)
}
func (m *ListCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCommentsResponse.Size(m)
}
func (m *ListCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommentsResponse proto.InternalMessageInfo

func (m *ListCommentsResponse) GetComments() []*SingleComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *ListCommentsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCommentsResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type SingleComment struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserUid              string               `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	PostUid              string               `protobuf:"bytes,3,opt,name=postUid,proto3" json:"postUid,omitempty"`
	Body                 string               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ParentUid            string               `protobuf:"bytes,5,opt,name=parentUid,proto3" json:"parentUid,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SingleComment) Reset()         { *m = SingleComment{} }
func (m *SingleComment) String() string { return proto.CompactTextString(m) }
func (*SingleComment) ProtoMessage()    {}
func (*SingleComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{2}
}

func (m *SingleComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleComment.Unmarshal(m, b)
}
func (m *SingleComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleComment.Marshal(b, m, deterministic)
}
func (m *SingleComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleComment.Merge(m, src)
}
func (m *SingleComment) XXX_Size() int {
	return xxx_messageInfo_SingleComment.Size(m)
}
func (m *SingleComment) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleComment.DiscardUnknown(m)
}

var xxx_messageInfo_SingleComment proto.InternalMessageInfo

func (m *SingleComment) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SingleComment) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *SingleComment) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *SingleComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SingleComment) GetParentUid() string {
	if m != nil {
		return m.ParentUid
	}
	return ""
}

func (m *SingleComment) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SingleComment) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type CreateCommentRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ParentUid            string   `protobuf:"bytes,4,opt,name=parentUid,proto3" json:"parentUid,omitempty"`
	UserUid              string   `protobuf:"bytes,5,opt,name=userUid,proto3" json:"userUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{3}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateCommentRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *CreateCommentRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateCommentRequest) GetParentUid() string {
	if m != nil {
		return m.ParentUid
	}
	return ""
}

func (m *CreateCommentRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type UpdateCommentRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCommentRequest) Reset()         { *m = UpdateCommentRequest{} }
func (m *UpdateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCommentRequest) ProtoMessage()    {}
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{4}
}

func (m *UpdateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCommentRequest.Unmarshal(m, b)
}
func (m *UpdateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCommentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCommentRequest.Merge(m, src)
}
func (m *UpdateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCommentRequest.Size(m)
}
func (m *UpdateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCommentRequest proto.InternalMessageInfo

func (m *UpdateCommentRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateCommentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateCommentRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateCommentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCommentResponse) Reset()         { *m = UpdateCommentResponse{} }
func (m *UpdateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCommentResponse) ProtoMessage()    {}
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{5}
}

func (m *UpdateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCommentResponse.Unmarshal(m, b)
}
func (m *UpdateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCommentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCommentResponse.Merge(m, src)
}
func (m *UpdateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCommentResponse.Size(m)
}
func (m *UpdateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCommentResponse proto.InternalMessageInfo

type DeleteCommentRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentRequest) Reset()         { *m = DeleteCommentRequest{} }
func (m *DeleteCommentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentRequest) ProtoMessage()    {}
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{6}
}

func (m *DeleteCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentRequest.Unmarshal(m, b)
}
func (m *DeleteCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentRequest.Merge(m, src)
}
func (m *DeleteCommentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentRequest.Size(m)
}
func (m *DeleteCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentRequest proto.InternalMessageInfo

func (m *DeleteCommentRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteCommentRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeleteCommentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCommentResponse) Reset()         { *m = DeleteCommentResponse{} }
func (m *DeleteCommentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCommentResponse) ProtoMessage()    {}
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{7}
}

func (m *DeleteCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCommentResponse.Unmarshal(m, b)
}
func (m *DeleteCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCommentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCommentResponse.Merge(m, src)
}
func (m *DeleteCommentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCommentResponse.Size(m)
}
func (m *DeleteCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCommentResponse proto.InternalMessageInfo

type GetTokenRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{8}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetTokenRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5186d1a296b1a7f5, []int{9}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCommentsRequest)(nil), "comment.ListCommentsRequest")
	proto.RegisterType((*ListCommentsResponse)(nil), "comment.ListCommentsResponse")
	proto.RegisterType((*SingleComment)(nil), "comment.SingleComment")
	proto.RegisterType((*CreateCommentRequest)(nil), "comment.CreateCommentRequest")
	proto.RegisterType((*UpdateCommentRequest)(nil), "comment.UpdateCommentRequest")
	proto.RegisterType((*UpdateCommentResponse)(nil), "comment.UpdateCommentResponse")
	proto.RegisterType((*DeleteCommentRequest)(nil), "comment.DeleteCommentRequest")
	proto.RegisterType((*DeleteCommentResponse)(nil), "comment.DeleteCommentResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "comment.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "comment.GetTokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentClient interface {
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*SingleComment, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type commentClient struct {
	cc *grpc.ClientConn
}

func NewCommentClient(cc *grpc.ClientConn) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*SingleComment, error) {
	out := new(SingleComment)
	err := c.cc.Invoke(ctx, "/comment.Comment/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/UpdateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/comment.Comment/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
type CommentServer interface {
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*SingleComment, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
}

func RegisterCommentServer(s *grpc.Server, srv CommentServer) {
	s.RegisterService(&_Comment_serviceDesc, srv)
}

func _Comment_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.Comment/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comment.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComments",
			Handler:    _Comment_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _Comment_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _Comment_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Comment_DeleteComment_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Comment_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/comment/proto/comment.proto",
}

func init() {
	proto.RegisterFile("services/comment/proto/comment.proto", fileDescriptor_5186d1a296b1a7f5)
}

var fileDescriptor_5186d1a296b1a7f5 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x8f, 0xd3, 0x3c,
	0x10, 0x56, 0x92, 0x76, 0xdb, 0xce, 0xbe, 0xd5, 0xbb, 0x32, 0x01, 0x42, 0xb4, 0x2c, 0x55, 0xc4,
	0x21, 0xa7, 0x54, 0x2a, 0x17, 0xc4, 0x01, 0x84, 0x96, 0x0f, 0x21, 0x50, 0x0f, 0xe9, 0xee, 0x0f,
	0x48, 0x9b, 0xd9, 0x2a, 0xa2, 0xa9, 0x4d, 0xec, 0x20, 0xc1, 0x0f, 0xe0, 0xc2, 0x8d, 0xff, 0x8b,
	0x40, 0x49, 0xec, 0xc4, 0x29, 0x2e, 0x20, 0x6e, 0x99, 0xaf, 0xc7, 0x33, 0xcf, 0x33, 0x13, 0x78,
	0xc8, 0xb1, 0xf8, 0x98, 0x6d, 0x90, 0xcf, 0x37, 0x34, 0xcf, 0x71, 0x2f, 0xe6, 0xac, 0xa0, 0x82,
	0x2a, 0x2b, 0xaa, 0x2d, 0x32, 0x92, 0xa6, 0xff, 0x60, 0x4b, 0xe9, 0x76, 0x87, 0x4d, 0xd2, 0xba,
	0xbc, 0x99, 0x8b, 0x2c, 0x47, 0x2e, 0x92, 0x9c, 0x35, 0x99, 0xc1, 0x57, 0x0b, 0x6e, 0xbd, 0xcb,
	0xb8, 0xb8, 0x6c, 0x0a, 0x78, 0x8c, 0x1f, 0x4a, 0xe4, 0x82, 0x78, 0x30, 0x62, 0x94, 0x8b, 0xeb,
	0x2c, 0xf5, 0xac, 0x99, 0x15, 0x4e, 0x62, 0x65, 0x92, 0x0b, 0x00, 0x89, 0x5e, 0x05, 0xed, 0x3a,
	0xa8, 0x79, 0x88, 0x0f, 0x63, 0x96, 0x6c, 0x71, 0x95, 0x7d, 0x46, 0xcf, 0x99, 0x59, 0xe1, 0x30,
	0x6e, 0xed, 0xaa, 0xb6, 0xfa, 0x5e, 0x96, 0xf9, 0x1a, 0x0b, 0x6f, 0x50, 0x47, 0x35, 0x4f, 0xf0,
	0xc5, 0x02, 0xb7, 0xdf, 0x0d, 0x67, 0x74, 0xcf, 0x91, 0x2c, 0x60, 0x2c, 0x9f, 0xe0, 0x9e, 0x35,
	0x73, 0xc2, 0xd3, 0xc5, 0x9d, 0x48, 0x8d, 0xbc, 0xca, 0xf6, 0xdb, 0x1d, 0xca, 0x92, 0xb8, 0xcd,
	0xeb, 0x35, 0x62, 0xff, 0xb6, 0x11, 0xe7, 0x97, 0x46, 0xbe, 0x5b, 0x30, 0xed, 0xe1, 0x92, 0x33,
	0x70, 0xca, 0x96, 0x8c, 0xea, 0xb3, 0xa2, 0xa8, 0xe4, 0x58, 0x74, 0x2c, 0x28, 0x53, 0x27, 0xcf,
	0xe9, 0x93, 0x47, 0x60, 0xb0, 0xa6, 0xe9, 0xa7, 0x7a, 0xf4, 0x49, 0x5c, 0x7f, 0x93, 0x73, 0x98,
	0xb0, 0xa4, 0x90, 0x7c, 0x0e, 0xeb, 0x40, 0xe7, 0x20, 0x8f, 0x61, 0xb2, 0x29, 0x30, 0x11, 0x98,
	0x3e, 0x17, 0xde, 0xc9, 0xcc, 0x0a, 0x4f, 0x17, 0x7e, 0xd4, 0xa8, 0x1a, 0x29, 0x55, 0xa3, 0x2b,
	0xa5, 0x6a, 0xdc, 0x25, 0x93, 0x27, 0x00, 0x39, 0x4d, 0xb3, 0x9b, 0xac, 0x2e, 0x1d, 0xfd, 0xb1,
	0x54, 0xcb, 0x0e, 0xbe, 0x59, 0xe0, 0x5e, 0xd6, 0x48, 0x8a, 0x57, 0xb9, 0x17, 0x2e, 0x0c, 0x05,
	0x7d, 0x8f, 0x7b, 0x49, 0x44, 0x63, 0xe8, 0x03, 0xdb, 0xe6, 0x81, 0x9d, 0x63, 0x03, 0x0f, 0x0e,
	0x07, 0xd6, 0x68, 0x1d, 0xf6, 0x68, 0x0d, 0x62, 0x70, 0xaf, 0x59, 0xfa, 0xb7, 0x3d, 0x49, 0xc1,
	0xec, 0x4e, 0x30, 0x43, 0x2f, 0xc1, 0x5d, 0xb8, 0x7d, 0x80, 0xd9, 0x6c, 0x5c, 0xf0, 0x14, 0xdc,
	0x17, 0xb8, 0xc3, 0x7f, 0x7d, 0xac, 0x02, 0x3e, 0xa8, 0x97, 0xc0, 0x2f, 0xe1, 0xff, 0xd7, 0x28,
	0xae, 0xaa, 0x32, 0x0d, 0x33, 0x61, 0xec, 0x8d, 0xda, 0xae, 0xc6, 0xa8, 0x68, 0x4a, 0x18, 0x5b,
	0xe1, 0xa6, 0x40, 0x21, 0x91, 0x3b, 0x47, 0x10, 0xc2, 0x59, 0x07, 0x23, 0xaf, 0xc4, 0xd8, 0xdb,
	0xe2, 0x87, 0x0d, 0x23, 0xb5, 0xc5, 0x6f, 0xe1, 0x3f, 0xfd, 0xbe, 0xc8, 0x79, 0x7b, 0x45, 0x86,
	0x9f, 0x80, 0x7f, 0xff, 0x48, 0x54, 0x3e, 0xf7, 0x0a, 0xa6, 0xbd, 0x1d, 0x21, 0x5d, 0xbe, 0x69,
	0x77, 0xfc, 0x23, 0x27, 0x4b, 0x96, 0x30, 0xed, 0x69, 0xa0, 0xe1, 0x98, 0xf4, 0xf6, 0x2f, 0x8e,
	0x85, 0x65, 0x5f, 0x4b, 0x98, 0xf6, 0xa8, 0xd7, 0xf0, 0x4c, 0x92, 0x6a, 0x78, 0x46, 0xc5, 0xc8,
	0x33, 0x18, 0x2b, 0xaa, 0x89, 0xd7, 0xe6, 0x1e, 0x88, 0xe8, 0xdf, 0x33, 0x44, 0x1a, 0x80, 0xf5,
	0x49, 0x7d, 0x6d, 0x8f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x9d, 0x56, 0x74, 0xbd, 0x05,
	0x00, 0x00,
}
