CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS moddatetime;

CREATE TABLE comments (
    uid UUID PRIMARY KEY DEFAULT,
    post_uid UUID NOT NULL,
    body TEXT NOT NULL,
    parent_uid UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL
);
